### ISSUE TITLE
IE

### ISSUE THREAD

**Issue by Zauberfisch** [unclecheese/KickAssets#15]
I have read your comment on leftandmain.com and the prev issue on here about IE, but I still wish to bring up this topic again.

I think drag & drop support for IE is out of question, but with some quick changes we could show the IE users a normal uploadify field or even just a normal html form browse button.

Telling a user he has to use another browser is normally fine to me.
but sometimes you have clients that have no other choice then using IE, in that case you can at least tell them that it works in IE, but works way better in a proper browser.

first thing is that in IE if you open a folder, you get a error.
[Notice] Trying to get property of non-object
Problem is, the url is "admin/files/admin/files/browse/1" and not "admin/files/browse/1" as it should be.
simple fix: kickassets.js, Line 388
replace "window.location.href = $t.data('link');" with "window.location.href = '/'.$t.data('link');"
With that simple fix, a IE user can at least browse the files.

**Comment by unclecheese** [comment]
I'm not terribly interested in developing support for IE mostly because I don't have access to it. If someone wants to fork the code and add support, that's fine with me, but I don't want to put a lot of time into adding support for these sorts of edge cases. I will take a look at that one patch, though.
