### ISSUE TITLE
More Call-time pass-by-reference has been deprecated

### ISSUE THREAD

**Issue by MarcusDalgren** [unclecheese/KickAssets#5]
Umm I just downloaded the latest version and there's still an ampersand in there. The code looks like this:
if(version_compare(PHP_VERSION, '5.3')) {
$file->updateCMSFields(&$fields);

}
else {
$file->updateCMSFields($fields);
}
I'm running version 5.2.11 but I'm still getting an error related to this. 
It's on line 600 in KickAssetAdmin.php.

**Comment by MarcusDalgren** [comment]
I switched to php 5.3.5 and I don't get any errors in PHP 5.3 either when removing the ampersand.
My code now reads:
if($file->hasMethod('updateCMSFields')) {
    $file->updateCMSFields($fields);  
}

Does it need to be passed as a true reference or is it sufficient with a normal PHP object reference?

**Comment by unclecheese** [comment]
So here's the thing.. they're both wrong. Since PHP 5.0, objects are passed as references by default. The &$fields we use in our updateCMSFields() functions are not necessary. They're legacy from when SS was on PHP 4. That's why to create a true copy of an object, you need to use the "clone" keyword.

$a->Foo = "bar";
$b = $a;
$b->Foo = "foo";
echo $a->Foo;
// returns "foo";

$a->Foo = "bar";
$b = clone $a;
$b->Foo = "foo";
echo $a->Foo;
// returns "bar";

SilverStripe should just get rid of the & in their updateCMSFields function. That's the long-term solution that makes the most sense. Both 5.2. and 5.3 are conflicted on how to handle a deprecated way of doing something, so we just version_compare() our way out of it for now.
